import type { TemplateDocument } from "@/components/documents/pdf-styles";

/* ================================================================
   INVESTOR DOCUMENT CONTENT
   4 template documents for investor-facing governance
   Major expansion from original skeletal HTML versions
   ================================================================ */

export const investorTermsAndConditions: TemplateDocument = {
  title: "Investor Terms",
  subtitle: "Investment Participation Agreement",
  ref: "SD-ITC-2026",
  version: "2.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: 'These Investor Terms & Conditions ("Terms") govern the relationship between Keenan Husselmann, trading as Swift Designz ("the Operator"), and any individual or entity that contributes capital to a Swift Designz project ("Investor"). By signing a Project Investment Agreement or transferring funds, the Investor unconditionally accepts these Terms.',
    },
    {
      type: "section",
      number: "01",
      title: "Definitions & Interpretation",
      bullets: [
        '"Operator" \u2014 Keenan Husselmann, an individual freelancer trading as Swift Designz. Swift Designz is not a registered company.',
        '"Investor" \u2014 An individual or entity that provides capital to fund a specified Swift Designz project in exchange for a defined return.',
        '"Investment" \u2014 The monetary amount contributed by the Investor for a specific project, as documented in the Project Investment Agreement.',
        '"Project" \u2014 A specific client engagement or internal product for which investment capital is sought and deployed.',
        '"ROI" \u2014 Return on Investment \u2014 the agreed percentage or fixed return payable to the Investor upon project completion and payment collection.',
        '"Project Investment Agreement" \u2014 A separate, project-specific document that defines the investment amount, project details, ROI terms, and payout schedule for each investment.',
        '"Payout" \u2014 The transfer of returns (principal + ROI) from Swift Designz to the Investor.',
      ],
    },
    {
      type: "section",
      number: "02",
      title: "Nature of Investment",
      bullets: [
        "Investments are project-specific. Each investment is tied to a single defined project and documented in a separate Project Investment Agreement.",
        "Investments are not equity. The Investor does not acquire any ownership stake, shares, voting rights, or partnership interest in Swift Designz or any of its assets.",
        "The relationship is that of a creditor providing project capital, not a partner, shareholder, or joint-venture participant.",
        "Swift Designz retains full operational control over all projects, including client relationships, scope, pricing, staffing, and execution approach.",
        "Investors may not direct, manage, or interfere with the delivery of any project. Investment confers financial participation only.",
      ],
    },
    {
      type: "section",
      number: "03",
      title: "Investment Process",
      bullets: [
        "Step 1: Opportunity Presented \u2014 Swift Designz identifies a project requiring external capital and presents the opportunity to qualified investors via the Investor Portal or direct communication.",
        "Step 2: Due Diligence \u2014 The Investor reviews the project details, estimated timeline, ROI terms, and risk factors. Investors are encouraged to conduct their own due diligence.",
        "Step 3: Agreement Signed \u2014 Both parties sign a Project Investment Agreement that documents the exact investment amount, project scope, expected timeline, and ROI terms.",
        "Step 4: Capital Transferred \u2014 The Investor transfers the agreed amount via EFT. The investment is confirmed upon receipt of funds.",
        "Step 5: Project Execution \u2014 Swift Designz delivers the project. The Investor receives progress updates as per the Reporting Policy (SD-IRP-2026).",
        "Step 6: Client Payment Collected \u2014 Swift Designz collects payment from the end client upon project delivery.",
        "Step 7: Investor Payout \u2014 The Investor receives their capital plus agreed ROI within 14 business days of client payment collection.",
      ],
    },
    {
      type: "section",
      number: "04",
      title: "Returns & Payout Terms",
      bullets: [
        "ROI terms are defined per project in the Project Investment Agreement. There is no guaranteed fixed rate across all investments.",
        "Indicative ROI range: 10\u201325% per project, depending on project size, risk profile, and duration. Actual terms are agreed per project.",
        "Payouts are calculated on the invested amount: Payout = Investment + (Investment \u00d7 ROI%).",
        "Payouts are processed within 14 business days of the Operator receiving full client payment for the funded project.",
        "All payouts are made via EFT to the bank account registered in the Investor\u2019s profile. The Investor is responsible for ensuring banking details are current.",
        "Partial payouts may be made where the client pays in instalments, proportional to the amount collected.",
      ],
    },
    {
      type: "section",
      number: "05",
      title: "Risk Acknowledgement",
      body: "By investing, the Investor acknowledges and accepts the following risks:",
      bullets: [
        "Client Default Risk: The end client may fail to pay, delay payment, or cancel the project. Swift Designz will make reasonable efforts to collect, but cannot guarantee client payment.",
        "Timeline Risk: Projects may take longer than estimated due to client delays, scope changes, or technical complexity. Extended timelines delay payout but do not reduce the agreed ROI.",
        "Scope Risk: Project scope may change during delivery. Material scope changes that affect the investment value will be communicated to the Investor promptly.",
        "Operational Risk: As a sole freelancer operation, Swift Designz is subject to capacity constraints, illness, or other personal circumstances that may affect delivery.",
        "No Guarantee of Return: While Swift Designz operates in good faith to deliver projects and collect payments, investment returns are not guaranteed. The Investor accepts the possibility of partial or delayed returns.",
        "No Deposit Insurance: Investments are not protected by any government deposit insurance scheme or financial guarantee.",
      ],
    },
    {
      type: "section",
      number: "06",
      title: "Investor Rights",
      bullets: [
        "Right to Information: Investors have the right to receive regular project status updates as defined in the Investor Reporting Policy (SD-IRP-2026).",
        "Right to Transparency: Investors may request clarification on any project milestone, financial summary, or payout calculation.",
        "Right to Exit: Investors may request early exit from an investment. See Section 09 (Early Exit & Cancellation) for terms.",
        "Right to Dispute: Investors may raise formal disputes. See Section 10 (Dispute Resolution) for the resolution process.",
        "Right to Privacy: Investor personal and financial data is protected under the Investor NDA (SD-INDA-2026) and applicable data protection laws.",
        "Right to Decline: Investors are never obligated to participate in any opportunity presented. Each investment is voluntary.",
      ],
    },
    {
      type: "section",
      number: "07",
      title: "Investor Obligations",
      bullets: [
        "Transfer the agreed investment amount within 5 business days of signing the Project Investment Agreement.",
        "Maintain accurate and current banking details in the Investor Portal for payout processing.",
        "Maintain confidentiality of all project details, client information, and financial data as per the Investor NDA (SD-INDA-2026).",
        "Not represent themselves as an employee, partner, or agent of Swift Designz to any third party.",
        "Not contact or interfere with any Swift Designz client directly. All client communication is managed solely by the Operator.",
        "Comply with all applicable tax obligations arising from investment returns. Swift Designz does not provide tax advice.",
      ],
    },
    {
      type: "section",
      number: "08",
      title: "Reporting & Communication",
      bullets: [
        "Formal reporting is governed by the Investor Reporting Policy (SD-IRP-2026).",
        "Investors receive: Monthly portfolio summaries, project milestone updates, and payout confirmations.",
        "Ad-hoc queries may be directed to keenan@swiftdesignz.co.za with the subject: \u201cInvestor Query \u2014 [Name]\u201d.",
        "Material changes to any funded project (scope, timeline, or risk profile) will be communicated within 48 hours.",
      ],
    },
    {
      type: "section",
      number: "09",
      title: "Early Exit & Cancellation",
      bullets: [
        "Pre-Deployment Exit: If the investment has not yet been deployed to a project (funds received but project not started), the Investor may request a full refund. Refund processed within 14 business days.",
        "Mid-Project Exit: Once capital has been deployed to an active project, early exit is subject to negotiation. The Investor may receive a partial return based on work completed and funds recoverable.",
        "Force Majeure: In cases of extraordinary circumstances (natural disaster, pandemic, government action) affecting project delivery, both parties will negotiate in good faith to find a fair resolution.",
        "Operator Cancellation: If Swift Designz cancels a project after receiving investment, the full investment amount is returned within 14 business days. No ROI is payable on cancelled projects.",
      ],
    },
    {
      type: "section",
      number: "10",
      title: "Dispute Resolution",
      bullets: [
        "Step 1: Direct Discussion \u2014 Both parties attempt to resolve the dispute through direct communication within 14 days of written notice.",
        "Step 2: Written Mediation \u2014 If unresolved, both parties exchange written positions and attempt mediation within 30 days.",
        "Step 3: Independent Mediation \u2014 If still unresolved, the matter is referred to an independent mediator agreed upon by both parties. Mediation costs are shared equally.",
        "Step 4: Legal Action \u2014 As a last resort, either party may pursue legal remedies through the relevant courts.",
      ],
    },
    {
      type: "section",
      number: "11",
      title: "Limitation of Liability",
      bullets: [
        "Swift Designz\u2019s total liability to the Investor is limited to the amount of the specific investment in question.",
        "Swift Designz is not liable for indirect, consequential, or incidental damages, including lost opportunity costs.",
        "The Operator is not liable for losses caused by client default, third-party service failures, or circumstances beyond reasonable control.",
        "The Investor acknowledges that all investments carry inherent risk and that past returns do not guarantee future performance.",
      ],
    },
    {
      type: "section",
      number: "12",
      title: "Data Protection & Privacy",
      body: "Swift Designz collects and processes Investor data (name, contact details, banking information, investment history) solely for the purpose of managing the investment relationship. Data is stored securely, accessed only by the Operator, and never shared with third parties without consent. The Investor may request access to, correction of, or deletion of their data at any time by contacting keenan@swiftdesignz.co.za.",
    },
    {
      type: "section",
      number: "13",
      title: "Governing Law & Jurisdiction",
      body: "These Terms are governed by the laws of Namibia (or as jointly agreed between both parties). Any legal proceedings shall be brought before the competent courts of the agreed jurisdiction.",
    },
    {
      type: "section",
      number: "14",
      title: "Amendments",
      body: "Swift Designz reserves the right to amend these Terms with 30 days\u2019 written notice to active investors. Amendments do not apply retroactively to existing Project Investment Agreements already signed. The current version is always available via the Investor Portal.",
    },
    { type: "divider" },
    {
      type: "info",
      text: "By signing a Project Investment Agreement or transferring funds to Swift Designz, the Investor confirms they have read, understood, and unconditionally accept these Investor Terms & Conditions.",
    },
    { type: "signatures", leftLabel: "Investor", rightLabel: "Swift Designz" },
  ],
};

export const investorNda: TemplateDocument = {
  title: "Investor NDA",
  subtitle: "Confidentiality Agreement for Investors",
  ref: "SD-INDA-2026",
  version: "2.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: 'This Non-Disclosure Agreement ("Agreement") is entered into between Keenan Husselmann, trading as Swift Designz ("the Operator"), and the Investor identified below. This Agreement protects confidential business, financial, and client information disclosed during the investment relationship.',
    },
    { type: "parties" },
    {
      type: "section",
      number: "01",
      title: "Purpose",
      body: "The purpose of this Agreement is to protect sensitive information exchanged between the Operator and the Investor during the course of their investment relationship. The Investor will have access to financial data, client details, project information, and business strategies that are proprietary to Swift Designz. This Agreement ensures that such information is handled with the utmost confidentiality.",
    },
    {
      type: "section",
      number: "02",
      title: "Confidential Information Defined",
      body: "Confidential Information includes, but is not limited to:",
      bullets: [
        "Financial Information: Revenue figures, profit margins, project costs, pricing structures, investment returns, cash flow data, and financial projections.",
        "Client Information: Client names, contact details, project briefs, contract values, payment histories, and all information relating to Swift Designz client relationships.",
        "Project Details: Scope documents, timelines, technical architectures, source code, design assets, and delivery methodologies for any project funded or otherwise.",
        "Business Strategy: Growth plans, market positioning, investor pipeline, partnership opportunities, service expansion plans, and competitive analysis.",
        "Investor Data: Information about other investors, their investment amounts, returns, and participation in any project.",
        "Portal & Systems: Access credentials, system architecture, security measures, and technical infrastructure of the Investor Portal and internal systems.",
        "Communications: All emails, messages, reports, and documents exchanged between the Operator and the Investor during the relationship.",
      ],
    },
    {
      type: "section",
      number: "03",
      title: "Obligations of the Investor",
      body: "The Investor agrees to:",
      bullets: [
        "Keep all Confidential Information strictly confidential and not disclose it to any third party without the prior written consent of the Operator.",
        "Use Confidential Information solely for the purpose of evaluating, monitoring, and managing their investment in Swift Designz projects.",
        "Not use any Confidential Information for personal gain, competitive advantage, or any purpose other than the investment relationship.",
        "Not copy, reproduce, or distribute any Confidential Information except as necessary for the Investor\u2019s personal records.",
        "Apply at least the same degree of care to protect Confidential Information as they apply to their own confidential information, but no less than reasonable care.",
        "Promptly notify the Operator of any actual or suspected unauthorised disclosure, access, or use of Confidential Information.",
        "Not contact, solicit, or engage with any Swift Designz client directly, for any purpose, without the Operator\u2019s written consent.",
        "Not disclose their status as an investor in Swift Designz projects to any Swift Designz client.",
      ],
    },
    {
      type: "section",
      number: "04",
      title: "Obligations of the Operator",
      body: "The Operator (Swift Designz) agrees to:",
      bullets: [
        "Protect the Investor\u2019s personal and financial data with appropriate security measures.",
        "Not disclose the Investor\u2019s identity, investment amounts, or financial details to any third party (including clients) without the Investor\u2019s written consent.",
        "Limit access to Investor data to the Operator only. No employees, contractors, or partners will access Investor data without justified need and appropriate confidentiality agreements.",
        "Maintain secure storage (encrypted, access-controlled) for all Investor-related documents and data.",
      ],
    },
    {
      type: "section",
      number: "05",
      title: "Exclusions",
      body: "The confidentiality obligations do not apply to information that:",
      bullets: [
        "Is or becomes publicly available through no fault of the Receiving Party.",
        "Was already known to the Receiving Party before disclosure, as evidenced by prior written records.",
        "Is independently developed by the Receiving Party without reference to the Confidential Information.",
        "Is required to be disclosed by applicable law, court order, or regulatory authority \u2014 provided the Disclosing Party is given reasonable prior notice and an opportunity to seek a protective order.",
      ],
    },
    {
      type: "section",
      number: "06",
      title: "Duration",
      body: "This Agreement is effective from the date of signing and remains in force for the duration of the investment relationship plus three (3) years from the date the last investment is fully settled (principal + ROI paid out). The confidentiality obligations regarding client information survive indefinitely.",
    },
    {
      type: "section",
      number: "07",
      title: "Return or Destruction of Information",
      body: "Upon termination of the investment relationship, or upon written request from the Operator, the Investor agrees to return or securely destroy all Confidential Information in their possession within 30 days. This includes physical documents, digital files, emails, and any copies. The Investor may retain a single copy of their own investment records (amounts, dates, returns) for personal tax and financial purposes.",
    },
    {
      type: "section",
      number: "08",
      title: "Remedies for Breach",
      bullets: [
        "Both parties acknowledge that a breach of this Agreement may cause irreparable harm for which monetary damages alone would be insufficient.",
        "In the event of a breach, the injured party is entitled to seek immediate injunctive relief in addition to any other remedies available at law.",
        "A material breach by the Investor may result in immediate termination of the investment relationship, forfeiture of future investment opportunities, and legal action to recover damages.",
        "A material breach by the Operator may entitle the Investor to early exit from all active investments at full capital value.",
        "The prevailing party in any legal action to enforce this Agreement is entitled to recover reasonable legal costs.",
      ],
    },
    {
      type: "section",
      number: "09",
      title: "Non-Solicitation & Non-Compete",
      bullets: [
        "The Investor agrees not to directly or indirectly solicit, engage, or contract with any Swift Designz client for competing services during the investment relationship and for 12 months after its termination.",
        "The Investor agrees not to use information gained through the investment relationship to establish or operate a competing freelance development or training service during the relationship and for 12 months after.",
        "These restrictions apply only to the extent that they are enforceable under applicable law.",
      ],
    },
    {
      type: "section",
      number: "10",
      title: "Governing Law",
      body: "This Agreement is governed by the laws of Namibia (or as jointly agreed). Disputes are resolved per the process defined in the Investor Terms & Conditions (SD-ITC-2026), Section 10.",
    },
    { type: "divider" },
    {
      type: "info",
      text: "By signing below, both parties confirm that they have read, understood, and agree to be bound by this Non-Disclosure Agreement.",
    },
    { type: "signatures", leftLabel: "Investor", rightLabel: "Swift Designz" },
  ],
};

export const investorReportingPolicy: TemplateDocument = {
  title: "Reporting Policy",
  subtitle: "Investor Communication & Reporting Standards",
  ref: "SD-IRP-2026",
  version: "2.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: "This Reporting Policy defines the communication standards, report types, schedules, and escalation procedures for all investors participating in Swift Designz projects. Transparent and timely reporting is a cornerstone of the investor relationship.",
    },
    {
      type: "section",
      number: "01",
      title: "Reporting Principles",
      bullets: [
        "Transparency: All material information affecting an investment is reported promptly and honestly.",
        "Consistency: Reports follow a standard format and schedule so investors can track progress reliably.",
        "Relevance: Reports focus on information that directly affects the investor\u2019s capital and returns.",
        "Timeliness: Scheduled reports are delivered on time. Urgent matters are communicated within 48 hours.",
        "Accessibility: All reports are available through the Investor Portal and via email.",
      ],
    },
    {
      type: "section",
      number: "02",
      title: "Report Types & Schedule",
    },
    {
      type: "table",
      headers: ["Report", "Frequency", "Delivery", "Content"],
      rows: [
        [
          "Portfolio Summary",
          "Monthly",
          "1st week of month",
          "Active investments, status, projected payouts",
        ],
        [
          "Project Milestone Update",
          "Per milestone",
          "Within 48 hrs of milestone",
          "Milestone achieved, next milestone, risks",
        ],
        [
          "Payout Confirmation",
          "Per payout",
          "On payout date",
          "Amount, breakdown, bank reference",
        ],
        [
          "Quarterly Review",
          "Quarterly",
          "End of Q1/Q2/Q3/Q4",
          "Full portfolio review, returns summary, outlook",
        ],
        [
          "Annual Summary",
          "Annually",
          "January (prior year)",
          "Total invested, total returned, ROI, tax summary",
        ],
        [
          "Ad-Hoc / Urgent",
          "As needed",
          "Within 48 hours",
          "Material changes, risks, delays, client issues",
        ],
      ],
      colWidths: [22, 15, 20, 43],
    },
    {
      type: "section",
      number: "03",
      title: "Monthly Portfolio Summary \u2014 Contents",
      body: "The monthly portfolio summary includes:",
      bullets: [
        "List of all active investments with current status (Active / On Hold / Completed / Collecting Payment).",
        "Project progress indicator (percentage or milestone stage).",
        "Expected payout date for each investment.",
        "Any flags, risks, or delays affecting active projects.",
        "Summary of payouts made during the reporting period.",
        "Total portfolio value (invested capital + accrued returns).",
      ],
    },
    {
      type: "section",
      number: "04",
      title: "Project Milestone Updates",
      body: "Project milestones that trigger an investor update:",
      bullets: [
        "Project Commenced: Capital deployed, work has started.",
        "Design Approved: Client has approved the design direction.",
        "Build Complete: Core development work is finished.",
        "Client Review: Deliverable submitted to the client for review.",
        "Client Approved: Client has accepted the deliverable.",
        "Invoice Sent: Final invoice sent to the client.",
        "Payment Received: Client payment confirmed.",
        "Payout Processed: Investor return has been transferred.",
      ],
    },
    {
      type: "section",
      number: "05",
      title: "Payout Reports",
      body: "Every payout is accompanied by a confirmation that includes:",
      bullets: [
        "Investment reference (Project Investment Agreement number).",
        "Original investment amount.",
        "ROI percentage applied.",
        "Gross payout amount (capital + return).",
        "Bank transfer reference number.",
        "Date of transfer.",
      ],
    },
    {
      type: "section",
      number: "06",
      title: "Escalation & Exception Reporting",
      body: "The following events trigger immediate (within 48 hours) communication to affected investors:",
      bullets: [
        "Client default or non-payment beyond 14 days of invoice due date.",
        "Project cancellation by the client or Swift Designz.",
        "Material scope change that affects project value or timeline by more than 20%.",
        "Force majeure events affecting project delivery.",
        "Any security breach affecting investor data.",
        "Operator incapacity or inability to deliver for more than 10 consecutive business days.",
      ],
    },
    {
      type: "section",
      number: "07",
      title: "Communication Channels",
    },
    {
      type: "table",
      headers: ["Channel", "Purpose", "Response Time"],
      rows: [
        ["Investor Portal", "Primary: Reports, portfolio view, documents", "Real-time (self-service)"],
        ["Email", "Formal communications, reports, payout confirmations", "Within 2 business days"],
        ["Scheduled Call", "Quarterly review or ad-hoc deep dive (by appointment)", "Scheduled in advance"],
      ],
      colWidths: [25, 45, 30],
    },
    {
      type: "section",
      number: "08",
      title: "Investor Queries",
      bullets: [
        'Investors may submit queries via email to keenan@swiftdesignz.co.za with subject: "Investor Query \u2014 [Name] \u2014 [Topic]".',
        "Standard queries are responded to within 2 business days.",
        "Urgent queries (relating to payout issues or data security) are responded to within 1 business day.",
        "Complex queries requiring research are acknowledged within 2 business days with a resolution target communicated.",
      ],
    },
    {
      type: "section",
      number: "09",
      title: "Data Retention & Access",
      bullets: [
        "All investor reports are retained for 5 years from the date of issue.",
        "Historical reports are accessible via the Investor Portal for the duration of the investment relationship.",
        "After the relationship ends, the Investor may request a complete data export within 30 days.",
        "Annual tax summaries are provided in January each year for the prior calendar year.",
      ],
    },
    {
      type: "section",
      number: "10",
      title: "Policy Amendments",
      body: "Swift Designz may amend this Reporting Policy with 30 days\u2019 written notice. Amendments are published to the Investor Portal and communicated via email. The current version is always available at the Investor Portal and referenced as SD-IRP-2026.",
    },
    { type: "divider" },
    {
      type: "info",
      text: "This policy is effective for all active investors and is incorporated by reference into the Investor Terms & Conditions (SD-ITC-2026). Questions or feedback on this policy may be directed to keenan@swiftdesignz.co.za.",
    },
  ],
};

export const investorGovernanceCharter: TemplateDocument = {
  title: "Governance Charter",
  subtitle: "Investor Relations & Governance Framework",
  ref: "SD-IGC-2026",
  version: "2.0",
  effective: "March 2026",
  blocks: [
    {
      type: "info",
      text: "This Governance Charter establishes the operational, ethical, and financial governance standards that Swift Designz commits to maintaining for all investor relationships. It defines the decision-making framework, conflict of interest policies, financial controls, and accountability measures.",
    },
    {
      type: "section",
      number: "01",
      title: "Governance Principles",
      bullets: [
        "Integrity: All investor dealings are conducted with honesty, fairness, and good faith.",
        "Transparency: Material information is disclosed proactively. Investors are never misled.",
        "Accountability: The Operator is personally accountable for all capital deployment, project delivery, and payout obligations.",
        "Prudence: Investment capital is deployed conservatively, with a preference for lower-risk projects with established client relationships.",
        "Fairness: All investors are treated equitably. No investor receives preferential terms, insider information, or priority access not available to others at their tier.",
      ],
    },
    {
      type: "section",
      number: "02",
      title: "Decision-Making Authority",
      body: "As a sole freelancer operation, decision-making authority rests with Keenan Husselmann (the Operator). The following framework governs decisions that affect investors:",
    },
    {
      type: "table",
      headers: ["Decision Type", "Authority", "Investor Notification"],
      rows: [
        ["Accept new client project", "Operator sole discretion", "None required"],
        ["Offer investment opportunity", "Operator sole discretion", "Opportunity presented to qualified investors"],
        ["Deploy investment capital to project", "Operator, after signed Project Investment Agreement", "Confirmation within 48 hours of deployment"],
        ["Change project scope (minor, <20%)", "Operator", "Included in next milestone report"],
        ["Change project scope (major, >20%)", "Operator with investor notification", "Immediate notification within 48 hours"],
        ["Modify ROI terms", "Mutual agreement required", "Written amendment to Project Investment Agreement"],
        ["Cancel a funded project", "Operator (with full capital return)", "Immediate notification + refund within 14 business days"],
        ["Accept new investor", "Operator sole discretion", "None required"],
        ["Modify governance policies", "Operator with 30-day notice", "Written notice to all active investors"],
      ],
      colWidths: [35, 35, 30],
    },
    {
      type: "section",
      number: "03",
      title: "Financial Controls",
      body: "Swift Designz maintains the following financial controls to protect investor capital:",
      bullets: [
        "Segregation of Purpose: Investment capital is tracked separately from operating income. Each investment is mapped to a specific project with clear cost and revenue accounting.",
        "No Co-Mingling for Unrelated Use: Investor capital is deployed only to the project specified in the Project Investment Agreement. Capital is never redirected to unrelated projects or personal expenses.",
        "Accurate Record-Keeping: All transactions (incoming investments, project costs, client payments, investor payouts) are recorded in the Swift Designz accounting system and available for investor review upon request.",
        "Payout Priority: Investor payouts are processed before operator profit distribution. Client payments are first allocated to investor obligations.",
        "Banking: All investment transactions are conducted through the Swift Designz business bank account. Details are provided in all investment documents.",
      ],
    },
    { type: "banking" },
    {
      type: "section",
      number: "04",
      title: "Conflict of Interest Policy",
      bullets: [
        "The Operator will disclose any situation where their personal interests may conflict with investor interests.",
        "The Operator will not invest their own capital in a project where external investors have already committed, unless disclosed to all investors in that project.",
        "Client relationships are managed solely by the Operator. Investors must not have a pre-existing relationship with the funded client that could create a conflict, or must disclose it before investing.",
        "If a conflict of interest is identified after investment, the affected investor will be notified and given the option to exit the investment at full capital value.",
        "The Operator will not accept investments from clients of Swift Designz for projects that directly involve that client.",
      ],
    },
    {
      type: "section",
      number: "05",
      title: "Risk Management",
      bullets: [
        "Client Vetting: Before offering an investment opportunity, the Operator assesses the client\u2019s payment history, project feasibility, and ability to pay.",
        "Scope Locking: Projects funded by investors have clearly defined scopes documented in the Project Investment Agreement. Scope creep is managed via the Change Request process (SD-CR-2026).",
        "Diversification Guidance: Investors are encouraged to spread their capital across multiple projects rather than concentrating in a single investment.",
        "Reserve Policy: Swift Designz maintains an operational reserve to cover short-term payout obligations in the event of minor client payment delays.",
        "Insurance: The Operator does not currently maintain professional indemnity insurance. This risk is disclosed to all investors.",
        "Contingency Communication: If the Operator becomes incapacitated, a designated emergency contact will notify all active investors within 5 business days. Emergency contact details are maintained securely.",
      ],
    },
    {
      type: "section",
      number: "06",
      title: "Ethical Standards",
      bullets: [
        "Swift Designz will not accept investments from proceeds of crime or engage in any form of money laundering.",
        "The Operator will not make misleading claims about projected returns, project timelines, or risk profiles.",
        "All marketing and investor communications will be factual, balanced, and include appropriate risk warnings.",
        "The Operator will not pressure or incentivise anyone to invest beyond their financial comfort level.",
        "Investor complaints are taken seriously and addressed within the timelines specified in the Dispute Resolution process (SD-ITC-2026, Section 10).",
      ],
    },
    {
      type: "section",
      number: "07",
      title: "Investor Tiers & Eligibility",
      body: "Swift Designz may operate investor tiers based on capital commitment and track record:",
      bullets: [
        "Standard Investor: Any individual meeting the minimum investment threshold for a specific project. Access to project-by-project investment opportunities.",
        "Preferred Investor: Investors with a track record of 3+ successful investments. May receive early access to new opportunities and priority communication.",
        "Strategic Partner: By invitation only. For investors contributing significant capital or strategic value. Custom terms negotiated per engagement.",
        "Tier classifications are at the sole discretion of the Operator and may change based on investment activity and relationship history.",
      ],
    },
    {
      type: "section",
      number: "08",
      title: "Compliance & Legal",
      bullets: [
        "Swift Designz operates as a freelance business and is not a registered financial services provider. Investment opportunities are offered on a private, relationship basis and do not constitute a public offering.",
        "The Operator is not registered as a collective investment scheme, fund manager, or financial advisor. Investors are advised to seek independent financial and tax advice.",
        "All investor agreements are governed by the laws of Namibia (or as jointly agreed). Disputes follow the resolution process in SD-ITC-2026.",
        "Swift Designz reserves the right to refuse or return any investment at its sole discretion, without providing reasons.",
      ],
    },
    {
      type: "section",
      number: "09",
      title: "Charter Amendments",
      body: "This Charter may be amended by the Operator with 30 days\u2019 written notice to all active investors. Amendments are published to the Investor Portal. Material changes (affecting financial controls, conflict of interest policy, or payout terms) require a 60-day notice period. The current version is always available via the Investor Portal.",
    },
    {
      type: "section",
      number: "10",
      title: "Accountability & Review",
      bullets: [
        "This Charter is reviewed annually by the Operator (January each year).",
        "Investor feedback on governance practices is welcomed and may be submitted via email at any time.",
        "Significant governance incidents (e.g. conflict of interest events, financial control failures, data breaches) are documented, investigated, and reported to affected investors within 5 business days.",
      ],
    },
    { type: "divider" },
    {
      type: "info",
      text: "This Governance Charter is effective for all active investor relationships and is incorporated by reference into the Investor Terms & Conditions (SD-ITC-2026). By participating as an investor, you acknowledge and accept the governance standards defined herein.",
    },
  ],
};
